// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetHistoryParams creates a new GetHistoryParams object
// with the default values initialized.
func NewGetHistoryParams() *GetHistoryParams {
	var ()
	return &GetHistoryParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetHistoryParamsWithTimeout creates a new GetHistoryParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetHistoryParamsWithTimeout(timeout time.Duration) *GetHistoryParams {
	var ()
	return &GetHistoryParams{

		timeout: timeout,
	}
}

// NewGetHistoryParamsWithContext creates a new GetHistoryParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetHistoryParamsWithContext(ctx context.Context) *GetHistoryParams {
	var ()
	return &GetHistoryParams{

		Context: ctx,
	}
}

// NewGetHistoryParamsWithHTTPClient creates a new GetHistoryParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetHistoryParamsWithHTTPClient(client *http.Client) *GetHistoryParams {
	var ()
	return &GetHistoryParams{
		HTTPClient: client,
	}
}

/*GetHistoryParams contains all the parameters to send to the API endpoint
for the get history operation typically these are written to a http.Request
*/
type GetHistoryParams struct {

	/*Base
	  Currency code ex: EUR

	*/
	Base *string
	/*EndAt*/
	EndAt *strfmt.Date
	/*StartAt*/
	StartAt *strfmt.Date
	/*Symbols*/
	Symbols []string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get history params
func (o *GetHistoryParams) WithTimeout(timeout time.Duration) *GetHistoryParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get history params
func (o *GetHistoryParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get history params
func (o *GetHistoryParams) WithContext(ctx context.Context) *GetHistoryParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get history params
func (o *GetHistoryParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get history params
func (o *GetHistoryParams) WithHTTPClient(client *http.Client) *GetHistoryParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get history params
func (o *GetHistoryParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBase adds the base to the get history params
func (o *GetHistoryParams) WithBase(base *string) *GetHistoryParams {
	o.SetBase(base)
	return o
}

// SetBase adds the base to the get history params
func (o *GetHistoryParams) SetBase(base *string) {
	o.Base = base
}

// WithEndAt adds the endAt to the get history params
func (o *GetHistoryParams) WithEndAt(endAt *strfmt.Date) *GetHistoryParams {
	o.SetEndAt(endAt)
	return o
}

// SetEndAt adds the endAt to the get history params
func (o *GetHistoryParams) SetEndAt(endAt *strfmt.Date) {
	o.EndAt = endAt
}

// WithStartAt adds the startAt to the get history params
func (o *GetHistoryParams) WithStartAt(startAt *strfmt.Date) *GetHistoryParams {
	o.SetStartAt(startAt)
	return o
}

// SetStartAt adds the startAt to the get history params
func (o *GetHistoryParams) SetStartAt(startAt *strfmt.Date) {
	o.StartAt = startAt
}

// WithSymbols adds the symbols to the get history params
func (o *GetHistoryParams) WithSymbols(symbols []string) *GetHistoryParams {
	o.SetSymbols(symbols)
	return o
}

// SetSymbols adds the symbols to the get history params
func (o *GetHistoryParams) SetSymbols(symbols []string) {
	o.Symbols = symbols
}

// WriteToRequest writes these params to a swagger request
func (o *GetHistoryParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Base != nil {

		// query param base
		var qrBase string
		if o.Base != nil {
			qrBase = *o.Base
		}
		qBase := qrBase
		if qBase != "" {
			if err := r.SetQueryParam("base", qBase); err != nil {
				return err
			}
		}

	}

	if o.EndAt != nil {

		// query param end_at
		var qrEndAt strfmt.Date
		if o.EndAt != nil {
			qrEndAt = *o.EndAt
		}
		qEndAt := qrEndAt.String()
		if qEndAt != "" {
			if err := r.SetQueryParam("end_at", qEndAt); err != nil {
				return err
			}
		}

	}

	if o.StartAt != nil {

		// query param start_at
		var qrStartAt strfmt.Date
		if o.StartAt != nil {
			qrStartAt = *o.StartAt
		}
		qStartAt := qrStartAt.String()
		if qStartAt != "" {
			if err := r.SetQueryParam("start_at", qStartAt); err != nil {
				return err
			}
		}

	}

	valuesSymbols := o.Symbols

	joinedSymbols := swag.JoinByFormat(valuesSymbols, "")
	// query array param symbols
	if err := r.SetQueryParam("symbols", joinedSymbols...); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
