// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetDateParams creates a new GetDateParams object
// with the default values initialized.
func NewGetDateParams() *GetDateParams {
	var ()
	return &GetDateParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetDateParamsWithTimeout creates a new GetDateParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetDateParamsWithTimeout(timeout time.Duration) *GetDateParams {
	var ()
	return &GetDateParams{

		timeout: timeout,
	}
}

// NewGetDateParamsWithContext creates a new GetDateParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetDateParamsWithContext(ctx context.Context) *GetDateParams {
	var ()
	return &GetDateParams{

		Context: ctx,
	}
}

// NewGetDateParamsWithHTTPClient creates a new GetDateParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetDateParamsWithHTTPClient(client *http.Client) *GetDateParams {
	var ()
	return &GetDateParams{
		HTTPClient: client,
	}
}

/*GetDateParams contains all the parameters to send to the API endpoint
for the get date operation typically these are written to a http.Request
*/
type GetDateParams struct {

	/*Date*/
	Date strfmt.Date

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get date params
func (o *GetDateParams) WithTimeout(timeout time.Duration) *GetDateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get date params
func (o *GetDateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get date params
func (o *GetDateParams) WithContext(ctx context.Context) *GetDateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get date params
func (o *GetDateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get date params
func (o *GetDateParams) WithHTTPClient(client *http.Client) *GetDateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get date params
func (o *GetDateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDate adds the date to the get date params
func (o *GetDateParams) WithDate(date strfmt.Date) *GetDateParams {
	o.SetDate(date)
	return o
}

// SetDate adds the date to the get date params
func (o *GetDateParams) SetDate(date strfmt.Date) {
	o.Date = date
}

// WriteToRequest writes these params to a swagger request
func (o *GetDateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param date
	if err := r.SetPathParam("date", o.Date.String()); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
